name: Check rails best practices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rails_best_practices:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run exec rails_best_practices
        run: |
          bundle exec rails_best_practices
